DROP TABLE GUESTBOOKCOMM;
DROP SEQUENCE COMMNUM;

CREATE SEQUENCE COMMNUM;

CREATE TABLE GUESTBOOKCOMM(
	COMMNUM NUMBER NOT NULL,
	BOARDNUM NUMBER NOT NULL,
	USERNAME VARCHAR2(500) NOT NULL,
	NICKNAME VARCHAR2(500) NOT NULL,
	GUESTBOOKCOMM VARCHAR2(400) NOT NULL,
	REPORTING_DATE DATE NOT NULL,
	A VARCHAR2(100),
	B VARCHAR2(100)
);

SELECT * FROM GUESTBOOKCOMM;
