DROP TABLE POSTSCOMM;
DROP SEQUENCE COMMNUM;
DROP SEQUENCE GROUPNO;

CREATE SEQUENCE COMMNUM;
CREATE SEQUENCE GROUPNO;

CREATE TABLE POSTSCOMM(
   COMMNUM NUMBER NOT NULL,   --댓글 번호
   BOARDNUM NUMBER NOT NULL,   --게시글 번호
   USERNAME VARCHAR2(500) NOT NULL,   --사용자이름
   POSTSCOMM VARCHAR2(400) NOT NULL,   --내용
   REPORTING_DATE DATE NOT NULL,      --날짜
   GROUPNO NUMBER NOT NULL,         --그룹번호
   GROUPSQ NUMBER NOT NULL,         --그룹순서
   TITLETAB NUMBER NOT NULL         --타이틀탭
);

SELECT * FROM POSTSCOMM;

select count(*) from postscomm where groupno='4' and titletab = '1'

